name: Build and publish
on: [push]

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  build:
    needs: [tests]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        runtime: [ linux-arm64 ]
        include:
        - runtime: linux-arm64
          os: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2
        if: startsWith(matrix.os, 'ubuntu') && matrix.runtime == 'linux-arm64'

      - name: Build & publish Caprine
        uses: therealartti/electron-builder-action@master
        if: startsWith(matrix.os, 'ubuntu') && matrix.runtime == 'linux-arm64'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          mac_certs: ${{ secrets.CSC_LINK }}
          mac_certs_password: ${{ secrets.CSC_KEY_PASSWORD }}
          args: '--arm64'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.snapcraft_token }}

      - name: Show .deb
        if: startsWith(matrix.os, 'ubuntu') && matrix.runtime == 'linux-arm64'
        run: echo $(find . -type f -name "*.deb")

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: bareboat-necessities/lysmarine_gen
          # A personal access token for the GitHub repository in which the release will be created and edited.
          # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
          repo_token: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
          file: build/*.deb
          file_glob: true
          tag: vTest
          overwrite: true
          body: "Release .deb"
        
