name: Tests
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
  workflow_call:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        runtime: [ linux-arm64 ]
        include:
        - runtime: linux-arm64
          os: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Run tests
        run: |
            npm ci
            npm test
